### ISSUE TITLE
自动化寻找指纹

### ISSUE THREAD

**Issue by aploium** [neargle/ver-observer#2]
遍历项目git的所有tag (即所有release) 追踪在所有release中最少变化和最多变化的文件  

最少变化即最稳定， 可以作为指纹  
最多变化可作为探测细分版本的依据   

而对于一些没有git，以压缩包发布的软件(特别是国内的)， 也可用类似的方式处理.  

同时也不只是md5， 也有一些稳定的文本字段可以作为指纹.  

btw: 看到你简历了，欢迎来我组，有比ver-observer强得多的指纹探测系统 😄

**Comment by aploium** [comment]
嘛还有另一些思路不能说

**Comment by neargle** [comment]
感谢~ 非常受用！
其实在写这个项目的时候，我有想过找你聊聊，但是博客里的邮箱无法接收。
![image](https://user-images.githubusercontent.com/7868679/37566767-7f36c4e6-2af8-11e8-87a7-59d6a2b3e683.png)
你前面所说的思路就是现在 ver-observer 用的思路。前段时间稍微挤出点时间实现了一下，虽然并没有真正实现自己的初衷。
后面提到思路，之前和P师傅聊过，他做出了一套很棒的系统。
其他的思路，也非常受用。后面的另一些不能说思路也很吊胃口，好奇！
你们团队的能力确实很强，非常期待！
